name = "packetsucht-forum"
main = "_worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "packetsucht-db"
database_id = "d2b8f4a9-2db3-4e95-9765-40a49b1b886f"

[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "packetsucht-images"
